// Generated by tools/generate_pc_lua_enum_tables.py; do not edit manually.
// enums.lua SHA-256: dce1892f51e4e645d66ac8ffb31d217e8c36a32457c1005dd128978141103dc5
#pragma once

#include <cstddef>
#include <cstdint>

namespace PcLuaEnumData {
struct Value { const char* key; std::int32_t value; };
struct Table { const char* name; const Value* values; std::size_t count; };
const Table* Tables(std::size_t* count);
} // namespace PcLuaEnumData
