#if defined(EXL_DIAGNOSTIC_STAGE) && (EXL_DIAGNOSTIC_STAGE == 144 || EXL_DIAGNOSTIC_STAGE == 145)
#include "saltynx_external_plugin_persistence_entry.cpp"
#elif defined(EXL_DIAGNOSTIC_STAGE) && (EXL_DIAGNOSTIC_STAGE == 133 || EXL_DIAGNOSTIC_STAGE == 134 || EXL_DIAGNOSTIC_STAGE == 135 || EXL_DIAGNOSTIC_STAGE == 136 || EXL_DIAGNOSTIC_STAGE == 137 || EXL_DIAGNOSTIC_STAGE == 138 || EXL_DIAGNOSTIC_STAGE == 139 || EXL_DIAGNOSTIC_STAGE == 140 || EXL_DIAGNOSTIC_STAGE == 141 || EXL_DIAGNOSTIC_STAGE == 142 || EXL_DIAGNOSTIC_STAGE == 143)
#include "../saltynx_external_plugin_entry.cpp"
#elif defined(EXL_DIAGNOSTIC_STAGE) && EXL_DIAGNOSTIC_STAGE != 6 && EXL_DIAGNOSTIC_STAGE != 7 && EXL_DIAGNOSTIC_STAGE != 8 && EXL_DIAGNOSTIC_STAGE != 9 && EXL_DIAGNOSTIC_STAGE != 11 && EXL_DIAGNOSTIC_STAGE != 12 && EXL_DIAGNOSTIC_STAGE != 13 && EXL_DIAGNOSTIC_STAGE != 14 && EXL_DIAGNOSTIC_STAGE != 15 && EXL_DIAGNOSTIC_STAGE != 16 && EXL_DIAGNOSTIC_STAGE != 17 && EXL_DIAGNOSTIC_STAGE != 45 && EXL_DIAGNOSTIC_STAGE != 48 && EXL_DIAGNOSTIC_STAGE != 88 && EXL_DIAGNOSTIC_STAGE != 89 && EXL_DIAGNOSTIC_STAGE != 102 && EXL_DIAGNOSTIC_STAGE != 104 && EXL_DIAGNOSTIC_STAGE != 108 && EXL_DIAGNOSTIC_STAGE != 109 && EXL_DIAGNOSTIC_STAGE != 110 && EXL_DIAGNOSTIC_STAGE != 112 && EXL_DIAGNOSTIC_STAGE != 118 && EXL_DIAGNOSTIC_STAGE != 127 && EXL_DIAGNOSTIC_STAGE != 128
#include "../diagnostic_entry.cpp"
#else
#include "../runtime_entry.cpp"
#endif
