#!/usr/bin/env python3
"""Generate the narrow enum surface referenced by the fixed Starterr source."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


TABLES = ("CollectibleType", "ItemPoolType", "RoomType", "LevelStage")
REFERENCE = re.compile(r"\b(?P<table>" + "|".join(TABLES) + r")\.(?P<key>[A-Z0-9_]+)")
ENTRY = re.compile(
    r"^\s*(?P<key>[A-Z0-9_]+)\s*=\s*(?P<value>-?\s*\d+|[A-Z0-9_]+)\s*,?"
)
QUALIFIED_ENTRY = re.compile(
    r"\b(?P<table>" + "|".join(TABLES) +
    r")\.(?P<key>[A-Z0-9_]+)\s*=\s*(?P<value>-?\s*\d+)"
)


def table_body(source: str, table: str) -> str:
    match = re.search(rf"\b{re.escape(table)}\s*=\s*\{{", source)
    if match is None:
        raise ValueError(f"missing enum table: {table}")
    start = source.index("{", match.start())
    depth = 0
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start + 1:index]
    raise ValueError(f"unterminated enum table: {table}")


def parse_table(source: str, table: str) -> dict[str, int]:
    entries: dict[str, int] = {}
    for line in table_body(source, table).splitlines():
        match = ENTRY.match(line)
        if match is None:
            continue
        key = match.group("key")
        if key in entries:
            raise ValueError(f"duplicate enum key: {table}.{key}")
        raw_value = match.group("value").replace(" ", "")
        if raw_value.lstrip("-").isdigit():
            entries[key] = int(raw_value)
        elif raw_value in entries:
            entries[key] = entries[raw_value]
        else:
            raise ValueError(f"unresolved enum alias: {table}.{key}={raw_value}")
    return entries


def parse_values(source: str) -> dict[str, dict[str, int]]:
    values = {table: parse_table(source, table) for table in TABLES}
    for match in QUALIFIED_ENTRY.finditer(source):
        table = match.group("table")
        key = match.group("key")
        value = int(match.group("value").replace(" ", ""))
        existing = values[table].get(key)
        if existing is not None and existing != value:
            raise ValueError(f"duplicate enum key: {table}.{key}")
        values[table][key] = value
    return values


def references(mod_source: str) -> dict[str, set[str]]:
    required = {table: set() for table in TABLES}
    for match in REFERENCE.finditer(mod_source):
        required[match.group("table")].add(match.group("key"))
    return required


def generate(enum_source: Path, mod_source: Path, output: Path) -> None:
    enum_bytes = enum_source.read_bytes()
    enum_text = enum_bytes.decode("utf-8")
    required = references(mod_source.read_text(encoding="utf-8"))
    values = parse_values(enum_text)
    selected: list[tuple[str, str, int]] = []
    for table in TABLES:
        for key in sorted(required[table]):
            if key not in values[table]:
                raise ValueError(f"missing Starterr enum key: {table}.{key}")
            selected.append((table, key, values[table][key]))

    lines = [
        "// Generated by tools/generate_starterr_enums.py; do not edit manually.",
        f"// enums.lua SHA-256: {hashlib.sha256(enum_bytes).hexdigest()}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace StarterrEnumData {",
        "struct Value { const char* table; const char* key; std::int32_t value; };",
        f"inline constexpr std::array<Value, {len(selected)}> kValues = {{{{",
    ]
    lines.extend(f'    {{"{table}", "{key}", {value}}},' for table, key, value in selected)
    lines.extend(["}};", "} // namespace StarterrEnumData", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--enum-source", type=Path, required=True)
    parser.add_argument("--mod-source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    try:
        generate(arguments.enum_source, arguments.mod_source, arguments.output)
    except (OSError, UnicodeDecodeError, ValueError) as error:
        print(f"generate_starterr_enums: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
